project:
  type: book

lang: en


book:
  title: "TP : Apprentissage automatique et contrôle stochastique"
  author: "Samy Mekkaoui"
  date: today
  repo-url: "https://github.com/SamyMekk/TP-Controle-Stochastique"
  chapters:
     - index.qmd

     - part: "Part n°1  : Reinforcement Learning"
       chapters:
         - contents/RL/RappelsRL.qmd 
         - contents/RL/TP1.qmd
     - part: "Part n°2 : DeepPDE"
       chapters:
         - contents/DeepPDE/RappelsDeepPDE.qmd
         - contents/DeepPDE/TP2.qmd
     - part: "Part n°3 : Generative IA"
       chapters:
         - contents/GenerativeIA/RappelsGenAI.qmd
         - contents/GenerativeIA/TP3.qmd
 
     - references.qmd

    
     

  sidebar:
    style: docked

format:
  html:
    mainfont: "Computer Modern Serif"
    theme:
      light: simplex
      dark: solar
    css: utils/styles.css
    include-before-body:
      - utils/macros
    toc: true
    sidebar: true 
 
  
bibliography : references.bib
nocite: |
  @*

execute:
  kernel: "Python appstatapp_tp2"
  echo : true

